apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-pong-claim # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: ping-pong-sc # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-claim # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: todo-app-sc # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi