#!/usr/bin/env sh
set -e

if [ $SERVER ]
then
  URL=$(wget --max-redirect=0 https://en.wikipedia.org/wiki/Special:Random 2>&1 | grep Location: | cut -d ' ' -f2)
  wget -O- --post-data="{\"content\":\"Read $URL\"}" --header='Content-Type:application/json' $SERVER
fi
