apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes: # Define volume
        - name: shared-log-output
          emptyDir: {}
      containers:
        - name: log-output-generator
          image: tniemi/dwk-log-output-generator:1.10
          volumeMounts:
            - name: shared-log-output
              mountPath: /app/files
        - name: log-output-server
          image: tniemi/dwk-log-output-server:1.10
          volumeMounts:
            - name: shared-log-output
              mountPath: /app/files
