apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-app-output
          persistentVolumeClaim:
            claimName: todo-app-claim
      containers:
        - name: todo-app
          image: tniemi/dwk-todo-app:2.6
          env:
          - name: PORT
            value: "3000"
          - name: PIC_URL
            value: "https://picsum.photos/1200"
          volumeMounts:
            - name: todo-app-output
              mountPath: /app/files
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: tniemi/dwk-todo-backend:2.2
          env:
          - name: PORT
            value: "3000"
